import { FieldType } from '../../../common/enums'

export let emptyItem = {
  radiatorID: 'Testing',
  titleInternational: '',
  titleOriginal: '',
  titleEN: '',
  titleFR: '',
  titleDE: '',
  titleES: '',
  loglineEN: '',
  loglineFR: '',
  loglineDE: '',
  loglineES: '',
  synopsisShortEN: '',
  synopsisShortFR: '',
  synopsisShortDE: '',
  synopsisShortES: '',
  synopsisLongEN: '',
  synopsisLongFR: '',
  synopsisLongDE: '',
  synopsisLongES: '',
  duration: 0,
  productionYear: 0,
  productionMonth: 0,
  worldPremiereDate: null,
  status: null,
  framerate: null,
  ageRating: '',
  containsNudity: null,
  containsViolence: null,
  containsDrugUse: null,
  iMDBReviews: null,
  rottenTomatoesReviews: null,
  letterboxdReviews: null,
  iMDBRating: null,
  rottenTomatoesRating: null,
  letterboxdRating: null,
  filmFestivalViewers: null,
  tvStationViewers: null,
  vodViewers: null,
  boxOffice: null,
  previewByFilmCriticMagazine: '',
  previewByFilmCritic: '',
  reviewByFilmCriticMagazine: '',
  reviewByFilmCritic: '',
  facebookFanPageURL: '',
  instagramProfileURL: '',
  twitterProfileURL: '',
  websiteOfficial: '',
  iMDbLink: '',
  tMDBLink: '',
  letterboxdPage: '',
  justWatchPage: '',
  filmfreewayPage: '',
  audioFormat: '',
  aspectRatio: null,
  masterShootingMedium: null,
  masterShootingFormat: '',
  cameraUsed: '',
  lensesUsed: '',
  editingSoftwareUsed: '',
  threeDSoftwareUsed: '',
  vFXSoftwareUsed: '',
  animationTechniqueUsed: '',
  isFilmhubPosterCreated: null,
  isFilmhubPortraitStillCreated: null,
  isFilmhubLandscapeStillCreated: null,
  isFilmhubLandscapeExtra01StillCreated: null,
  isFilmhubLandscapeExtra02StillCreated: null,
  isFilmhubLandscapeExtra03StillCreated: null,
  isFilmhubLandscapeExtra04StillCreated: null,
  isFilmfriendPortraitCoverCreated: null,
  isFilmfriendLandscapeCoverCreated: null,
  isFilmfriendThumbnailCreated: null,
  isFilmfriendSliderCreated: null,
  isFilmfriendBackgroundCreated: null,
  isFilmfriendMaterialsOkQualityCheckPlatform: null,
  filmhubPosterLocation: '',
  filmhubPortraitStillLocation: '',
  filmhubLandscapeStillLocation: '',
  filmhubLandscapeExtra01StillLocation: '',
  filmhubLandscapeExtra02StillLocation: '',
  filmhubLandscapeExtra03StillLocation: '',
  filmhubLandscapeExtra04StillLocation: '',
  filmhubMaterialsOkQualityCheckPlatform: '',
  filmfriendPortraitCoverLocation: '',
  filmfriendLandscapeCoverLocation: '',
  filmfriendThumbnailLocation: '',
  filmfriendSliderLocation: '',
  filmfriendBackgroundLocation: '',
  vuulrVimeoLinkFilm: '',
  vuulrVimeoLinkTrailer: '',
  filmfreewayVimeoLinkFilm: '',
  festhomeVimeoLinkFilm: '',
  youtubeTrailerFHDRadiatorChannel: '',
  youtubeTrailer4KUHDRadiatorChannel: '',
  vimeoTrailerRadiatorWebsite: '',
  vimeoTrailerPublic: '',
  vimeoScreenerProduction: '',
  vimeoScreenerDirector: '',
  vimeoScreenerCrew: '',
  vimeoScreenerDOP: '',
  vimeoScreenerProgrammers: '',
  vimeoScreenerBuyers: '',
  vimeoScreenerPress: '',
  vimeoOnDemandFHD: '',
  vimeoOnDemand4KUHD: '',
  amazonUS: '',
  amazonUK: '',
  amazonDE: '',
  amazonES: '',
  tubi: '',
  dindintv: '',
  kisKisKeepItShortEN: '',
  kisKisKeepItShortES: '',
  kisKisKeepItShortDE: '',
  kisKisKeepItShortFR: '',
  bekkesShortFilms: '',
  wocomoMovies: '',
  wocomoHumanity: '',
  filmfriend: '',
  amazonIMDBTV: '',
  filmzie: '',
  fearless: '',
  overdrive: '',
  kinoscope: '',
  sofytv: '',
  daFilms: '',
  argo: '',
  avaLibrary: '',
  cinesquare: '',
  cinesud: '',
  guideDoc: '',
  soonerBelgium: '',
  soonerGermany: '',
  criterionCollection: '',
  creedGlobalMedia: '',
  artexFilm: '',
  cineBooks: '',
  cinetree: '',
  flexNetTv: '',
  filxPremiere: '',
  filmocrazy: '',
  filmin: '',
  gayBingeTV: '',
  movieBloc: '',
}

export const columnsTable = [
  { field: 'radiatorID', header: 'Radiator ID', colGroup: 'ID' },
  { field: 'id', header: 'Neo4J UUID', hidden: true },
  { field: 'titleInternational', header: 'International Title', colGroup: 'General Info', isDefault: true },
  { field: 'titleOriginal', header: 'Original Title' },
  { field: 'loglineEN', header: 'EN Logline' },
  { field: 'synopsisShortEN', header: 'EN Synopsis' },
  { field: 'synopsisLongEN', header: 'EN Synopsis' },
  { field: 'duration', header: 'Duration', type: FieldType.DURATION },
  { field: 'productionYear', header: 'Production Year', type: FieldType.INTEGER, isDefault: true },
  { field: 'productionMonth', header: 'Production Month', type: FieldType.INTEGER },
  { field: 'worldPremiereDate', header: 'World Premier Date', type: FieldType.DATE },
  { field: 'status', header: 'Status', type: FieldType.DROPDOWN, options: 'filmStatuses', isDefault: true },
  { field: 'framerate', header: 'Framerate', type: FieldType.DROPDOWN, options: 'framerates' },
  { field: 'ageRating', header: 'Age Rating', colGroup: 'Parental Guidance' },
]
export const columnsForm = [
  { field: 'id', header: 'Neo4J UUID', hidden: true },
  { field: 'radiatorID', header: 'Radiator ID', colGroup: 'ID' },
  { field: 'titleInternational', header: 'International Title', colGroup: 'General Info' },
  { field: 'titleOriginal', header: 'Original Title' },
  { field: 'titleEN', header: 'EN Title' },
  { field: 'titleFR', header: 'FR Title' },
  { field: 'titleDE', header: 'DE Title' },
  { field: 'titleES', header: 'ES Title' },
  { field: 'loglineEN', header: 'EN Logline' },
  { field: 'loglineFR', header: 'FR Logline' },
  { field: 'loglineDE', header: 'DE Logline' },
  { field: 'loglineES', header: 'ES Logline' },
  { field: 'synopsisShortEN', header: 'EN Synopsis' },
  { field: 'synopsisShortFR', header: 'FR Synopsis' },
  { field: 'synopsisShortDE', header: 'DE Synopsis' },
  { field: 'synopsisShortES', header: 'ES Synopsis' },
  { field: 'synopsisLongEN', header: 'EN Synopsis' },
  { field: 'synopsisLongFR', header: 'FR Synopsis' },
  { field: 'synopsisLongDE', header: 'DE Synopsis' },
  { field: 'synopsisLongES', header: 'ES Synopsis' },
  { field: 'duration', header: 'Duration', type: FieldType.DURATION },
  { field: 'productionYear', header: 'Production Year', type: FieldType.INTEGER },
  { field: 'productionMonth', header: 'Production Month', type: FieldType.INTEGER },
  { field: 'worldPremiereDate', header: 'World Premier Date', type: FieldType.DATE },
  { field: 'status', header: 'Status', type: FieldType.DROPDOWN, options: 'filmStatuses' },
  { field: 'framerate', header: 'Framerate', type: FieldType.DROPDOWN, options: 'framerates' },
  { field: 'ageRating', header: 'Age Rating', colGroup: 'Parental Guidance' },
  { field: 'containsNudity', header: 'Contains Nudity', type: FieldType.BOOLEAN },
  { field: 'containsViolence', header: 'Contains Violence', type: FieldType.BOOLEAN },
  { field: 'containsDrugUse', header: 'Contains DrugUse Use', type: FieldType.BOOLEAN },
  { field: 'iMDBReviews', header: 'IMDB Reviews', type: FieldType.INTEGER, colGroup: 'Reviews' },
  { field: 'rottenTomatoesReviews', header: 'RottenTomatoes Reviews', type: FieldType.INTEGER },
  { field: 'letterboxdReviews', header: 'Letterboxd Reviews', type: FieldType.INTEGER },
  { field: 'iMDBRating', header: 'IMDB Ratings', type: FieldType.FLOAT, colGroup: 'Ratings' },
  { field: 'rottenTomatoesRating', header: 'RottenTomatoes Rating', type: FieldType.FLOAT },
  { field: 'letterboxdRating', header: 'Letterboxd Rating', type: FieldType.FLOAT },
  { field: 'filmFestivalViewers', header: 'Film Festival Viewers', type: FieldType.INTEGER, colGroup: 'Viewers' },
  { field: 'tvStationViewers', header: 'TV Station Viewers', type: FieldType.INTEGER },
  { field: 'vodViewers', header: 'VOD Viewers', type: FieldType.INTEGER },
  { field: 'boxOffice', header: 'Box Office', type: FieldType.INTEGER },
  { field: 'previewByFilmCriticMagazine', header: 'PREV Press', colGroup: 'Press' },
  { field: 'previewByFilmCritic', header: 'Critic Preview' },
  { field: 'reviewByFilmCriticMagazine', header: 'Magazine Review' },
  { field: 'reviewByFilmCritic', header: 'Critic Review' },
  { field: 'facebookFanPageURL', header: 'Facebook Fan Page URL', colGroup: 'Social Media' },
  { field: 'instagramProfileURL', header: 'URL Instagram' },
  { field: 'twitterProfileURL', header: 'URL Twitter' },
  { field: 'websiteOfficial', header: 'Website Official', colGroup: 'Links' },
  { field: 'iMDbLink', header: 'IMDB Link' },
  { field: 'tMDBLink', header: 'TMDB Link' },
  { field: 'letterboxdPage', header: 'Letterboxd Page' },
  { field: 'justWatchPage', header: 'JustWatch Page' },
  { field: 'filmfreewayPage', header: 'Filmfreeway Page' },
  { field: 'audioFormat', header: 'Audio Format', colGroup: 'Technical Info' },
  { field: 'aspectRatio', header: 'Aspect Ratio', type: FieldType.DROPDOWN, options: 'aspectRatios' },
  { field: 'masterShootingMedium', header: 'Master Shooting Medium', type: FieldType.DROPDOWN, options: 'shootingMediums' },
  { field: 'masterShootingFormat', header: 'Master Shooting Format' },
  { field: 'cameraUsed', header: 'Used Camera' },
  { field: 'lensesUsed', header: 'Used Lenses' },
  { field: 'editingSoftwareUsed', header: 'Editing Software Used' },
  { field: 'threeDSoftwareUsed', header: '3D Software Used' },
  { field: 'vFXSoftwareUsed', header: 'VFX Software Used' },
  { field: 'animationTechniqueUsed', header: 'Animation Technique Used' },
  { field: 'isFilmhubPosterCreated', header: 'Is FilmHub Poster Created', type: FieldType.BOOLEAN, colGroup: 'VOD Platforms Technical' },
  { field: 'isFilmhubPortraitStillCreated', header: 'Is FilmHub Portrait Still Created', type: FieldType.BOOLEAN },
  { field: 'isFilmhubLandscapeStillCreated', header: 'Is FilmHub Landscape Still Created', type: FieldType.BOOLEAN },
  { field: 'isFilmhubLandscapeExtra01StillCreated', header: 'Is FilmHub Landscape Extra 01 Still Created', type: FieldType.BOOLEAN },
  { field: 'isFilmhubLandscapeExtra02StillCreated', header: 'Is FilmHub Landscape Extra 02 Still Created', type: FieldType.BOOLEAN },
  { field: 'isFilmhubLandscapeExtra03StillCreated', header: 'Is FilmHub Landscape Extra 03 Still Created', type: FieldType.BOOLEAN },
  { field: 'isFilmhubLandscapeExtra04StillCreated', header: 'Is FilmHub Landscape Extra 04 Still Created', type: FieldType.BOOLEAN },
  { field: 'isFilmfriendPortraitCoverCreated', header: 'Is FilmFriend Portrait Cover Created', type: FieldType.BOOLEAN },
  { field: 'isFilmfriendLandscapeCoverCreated', header: 'is FilmFriend Landscape Cover Created', type: FieldType.BOOLEAN },
  { field: 'isFilmfriendThumbnailCreated', header: 'Is FilmFriend Thumbnail Created', type: FieldType.BOOLEAN },
  { field: 'isFilmfriendSliderCreated', header: 'Is FilmFriend Slider Created', type: FieldType.BOOLEAN },
  { field: 'isFilmfriendBackgroundCreated', header: 'Is FilmFriend Background Created', type: FieldType.BOOLEAN },
  { field: 'isFilmfriendMaterialsOkQualityCheckPlatform', header: 'Is FilmFriend Materials OK Quality Check Platform', type: FieldType.BOOLEAN },
  { field: 'filmhubPosterLocation', header: 'Filmhub PosterL Location' },
  { field: 'filmhubPortraitStillLocation', header: 'Location Filmhub' },
  { field: 'filmhubLandscapeStillLocation', header: 'Location Filmhub' },
  { field: 'filmhubLandscapeExtra01StillLocation', header: 'Location Filmhub' },
  { field: 'filmhubLandscapeExtra02StillLocation', header: 'Location Filmhub' },
  { field: 'filmhubLandscapeExtra03StillLocation', header: 'Location Filmhub' },
  { field: 'filmhubLandscapeExtra04StillLocation', header: 'Location Filmhub' },
  { field: 'filmhubMaterialsOkQualityCheckPlatform', header: 'Platform Filmhub' },
  { field: 'filmfriendPortraitCoverLocation', header: 'Location Filmfriend' },
  { field: 'filmfriendLandscapeCoverLocation', header: 'Location Filmfriend' },
  { field: 'filmfriendThumbnailLocation', header: 'Filmfriend Thumbnail Location' },
  { field: 'filmfriendSliderLocation', header: 'Filmfriend Slider Location' },
  { field: 'filmfriendBackgroundLocation', header: 'Filmfriend Background Location' },
  { field: 'vuulrVimeoLinkFilm', header: 'Vuulr Vimeo Film Link', colGroup: 'Platform Specific Links Vimeo' },
  { field: 'vuulrVimeoLinkTrailer', header: 'Vuulr Vimeo Trailer Link' },
  { field: 'filmfreewayVimeoLinkFilm', header: 'FilmFreeway Film Link' },
  { field: 'festhomeVimeoLinkFilm', header: 'Festhome Vimeo Film Link' },
  { field: 'youtubeTrailerFHDRadiatorChannel', header: 'Youtube Trailer FHD Radiator Channel', colGroup: 'Trailer Links' },
  { field: 'youtubeTrailer4KUHDRadiatorChannel', header: 'Youtube Trailer 4KUHD Radiator Channel' },
  { field: 'vimeoTrailerRadiatorWebsite', header: 'Vimeo Trailer Radiator Website' },
  { field: 'vimeoTrailerPublic', header: 'Vimeo Trailer Public' },
  { field: 'vimeoScreenerProduction', header: 'Vimeo Screener Production', colGroup: 'Screener Links' },
  { field: 'vimeoScreenerDirector', header: 'Vimeo Screener Director' },
  { field: 'vimeoScreenerCrew', header: 'Vimeo Screener Crew' },
  { field: 'vimeoScreenerDOP', header: 'Vimeo Screener DOP' },
  { field: 'vimeoScreenerProgrammers', header: 'Vimeo Screener Programmers' },
  { field: 'vimeoScreenerBuyers', header: 'Vimeo Screener Buyers' },
  { field: 'vimeoScreenerPress', header: 'Vimeo Screener Press' },
  { field: 'vimeoOnDemandFHD', header: 'Vimeo OnDemand FHD', colGroup: 'VOD Platforms Links' },
  { field: 'vimeoOnDemand4KUHD', header: 'Vimeo OnDemand 4KUHD' },
  { field: 'amazonUS', header: 'US Amazon' },
  { field: 'amazonUK', header: 'UK Amazon' },
  { field: 'amazonDE', header: 'DE Amazon' },
  { field: 'amazonES', header: 'ES Amazon' },
  { field: 'tubi', header: 'Tubi' },
  { field: 'dindintv', header: 'Dindintv' },
  { field: 'kisKisKeepItShortEN', header: 'EN KisKis Short' },
  { field: 'kisKisKeepItShortES', header: 'ES KisKis Short' },
  { field: 'kisKisKeepItShortDE', header: 'DE KisKis Short' },
  { field: 'kisKisKeepItShortFR', header: 'FR KisKis Short' },
  { field: 'bekkesShortFilms', header: 'Bekkes Short Films' },
  { field: 'wocomoMovies', header: 'Wocomo Movies' },
  { field: 'wocomoHumanity', header: 'Wocomo Humanity' },
  { field: 'filmfriend', header: 'Filmfriend' },
  { field: 'amazonIMDBTV', header: 'Amazon IMDBTV' },
  { field: 'filmzie', header: 'Filmzie' },
  { field: 'fearless', header: 'Fearless' },
  { field: 'overdrive', header: 'Overdrive' },
  { field: 'kinoscope', header: 'Kinoscope' },
  { field: 'sofytv', header: 'SofyTV' },
  { field: 'daFilms', header: 'DaFilms' },
  { field: 'argo', header: 'Argo' },
  { field: 'avaLibrary', header: 'Ava Library' },
  { field: 'cinesquare', header: 'Cinesquare' },
  { field: 'cinesud', header: 'Cinesud' },
  { field: 'guideDoc', header: 'GuideDoc' },
  { field: 'soonerBelgium', header: 'Sooner Belgium' },
  { field: 'soonerGermany', header: 'Sooner Germany' },
  { field: 'criterionCollection', header: 'Criterion Collection' },
  { field: 'creedGlobalMedia', header: 'Creed Global Media' },
  { field: 'artexFilm', header: 'ArtexFilm' },
  { field: 'cineBooks', header: 'CineBooks' },
  { field: 'cinetree', header: 'Cinetree' },
  { field: 'flexNetTv', header: 'FlexNetTV' },
  { field: 'filxPremiere', header: 'FlixPremier' },
  { field: 'filmocrazy', header: 'FilmoCrazy' },
  { field: 'filmin', header: 'Filmin' },
  { field: 'gayBingeTV', header: 'GayBingeTV' },
  { field: 'movieBloc', header: 'MovieBloc' },
]
