import { FieldType } from '../../../common/enums'

export let emptyItem = {
  radiatorID: 'Testing',
  titleInternational: '',
  titleOriginal: '',
  titleEN: '',
  titleFR: '',
  titleDE: '',
  titleES: '',
  loglineEN: '',
  loglineFR: '',
  loglineDE: '',
  loglineES: '',
  synopsisShortEN: '',
  synopsisShortFR: '',
  synopsisShortDE: '',
  synopsisShortES: '',
  synopsisLongEN: '',
  synopsisLongFR: '',
  synopsisLongDE: '',
  synopsisLongES: '',
  duration: 0,
  productionYear: 0,
  productionMonth: 0,
  worldPremiereDate: null,
  status: null,
  framerate: null,
  ageRating: '',
  containsNudity: null,
  containsViolence: null,
  containsDrugUse: null,
  iMDBReviews: null,
  rottenTomatoesReviews: null,
  letterboxdReviews: null,
  iMDBRating: null,
  rottenTomatoesRating: null,
  letterboxdRating: null,
  filmFestivalViewers: null,
  tvStationViewers: null,
  vodViewers: null,
  boxOffice: null,
  previewByFilmCriticMagazine: '',
  previewByFilmCritic: '',
  reviewByFilmCriticMagazine: '',
  reviewByFilmCritic: '',
  facebookFanPageURL: '',
  instagramProfileURL: '',
  twitterProfileURL: '',
  websiteOfficial: '',
  iMDbLink: '',
  tMDBLink: '',
  letterboxdPage: '',
  justWatchPage: '',
  filmfreewayPage: '',
  audioFormat: '',
  aspectRatio: null,
  masterShootingMedium: null,
  masterShootingFormat: '',
  cameraUsed: '',
  lensesUsed: '',
  editingSoftwareUsed: '',
  threeDSoftwareUsed: '',
  vFXSoftwareUsed: '',
  animationTechniqueUsed: '',
  isFilmhubPosterCreated: null,
  isFilmhubPortraitStillCreated: null,
  isFilmhubLandscapeStillCreated: null,
  isFilmhubLandscapeExtra01StillCreated: null,
  isFilmhubLandscapeExtra02StillCreated: null,
  isFilmhubLandscapeExtra03StillCreated: null,
  isFilmhubLandscapeExtra04StillCreated: null,
  isFilmfriendPortraitCoverCreated: null,
  isFilmfriendLandscapeCoverCreated: null,
  isFilmfriendThumbnailCreated: null,
  isFilmfriendSliderCreated: null,
  isFilmfriendBackgroundCreated: null,
  isFilmfriendMaterialsOkQualityCheckPlatform: null,
  filmhubPosterLocation: '',
  filmhubPortraitStillLocation: '',
  filmhubLandscapeStillLocation: '',
  filmhubLandscapeExtra01StillLocation: '',
  filmhubLandscapeExtra02StillLocation: '',
  filmhubLandscapeExtra03StillLocation: '',
  filmhubLandscapeExtra04StillLocation: '',
  filmhubMaterialsOkQualityCheckPlatform: '',
  filmfriendPortraitCoverLocation: '',
  filmfriendLandscapeCoverLocation: '',
  filmfriendThumbnailLocation: '',
  filmfriendSliderLocation: '',
  filmfriendBackgroundLocation: '',
  vuulrVimeoLinkFilm: '',
  vuulrVimeoLinkTrailer: '',
  filmfreewayVimeoLinkFilm: '',
  festhomeVimeoLinkFilm: '',
  youtubeTrailerFHDRadiatorChannel: '',
  youtubeTrailer4KUHDRadiatorChannel: '',
  vimeoTrailerRadiatorWebsite: '',
  vimeoTrailerPublic: '',
  vimeoScreenerProduction: '',
  vimeoScreenerDirector: '',
  vimeoScreenerCrew: '',
  vimeoScreenerDOP: '',
  vimeoScreenerProgrammers: '',
  vimeoScreenerBuyers: '',
  vimeoScreenerPress: '',
  vimeoOnDemandFHD: '',
  vimeoOnDemand4KUHD: '',
  amazonUS: '',
  amazonUK: '',
  amazonDE: '',
  amazonES: '',
  tubi: '',
  dindintv: '',
  kisKisKeepItShortEN: '',
  kisKisKeepItShortES: '',
  kisKisKeepItShortDE: '',
  kisKisKeepItShortFR: '',
  bekkesShortFilms: '',
  wocomoMovies: '',
  wocomoHumanity: '',
  filmfriend: '',
  amazonIMDBTV: '',
  filmzie: '',
  fearless: '',
  overdrive: '',
  kinoscope: '',
  sofytv: '',
  daFilms: '',
  argo: '',
  avaLibrary: '',
  cinesquare: '',
  cinesud: '',
  guideDoc: '',
  soonerBelgium: '',
  soonerGermany: '',
  criterionCollection: '',
  creedGlobalMedia: '',
  artexFilm: '',
  cineBooks: '',
  cinetree: '',
  flexNetTv: '',
  filxPremiere: '',
  filmocrazy: '',
  filmin: '',
  gayBingeTV: '',
  movieBloc: '',
}

export const columnsTable = [
  { field: 'radiatorID', header: 'Radiator ID', colGroup: 'ID' },
  { field: 'id', header: 'Neo4J UUID', hidden: true },
  { field: 'titleInternational', header: 'International Title', colGroup: 'General Info', isDefault: true },
  { field: 'titleOriginal', header: 'Original Title' },
  { field: 'loglineEN', header: 'EN Logline' },
  { field: 'synopsisShortEN', header: 'EN Synopsis' },
  { field: 'synopsisLongEN', header: 'EN Synopsis' },
  { field: 'duration', header: 'Duration', type: FieldType.DURATION },
  { field: 'productionYear', header: 'Production Year', type: FieldType.INTEGER, isDefault: true },
  { field: 'productionMonth', header: 'Production Month', type: FieldType.INTEGER },
  { field: 'worldPremiereDate', header: 'World Premier Date', type: FieldType.DATE },
  { field: 'status', header: 'Status', type: FieldType.DROPDOWN, options: 'filmStatuses', isDefault: true },
  { field: 'framerate', header: 'Framerate', type: FieldType.DROPDOWN, options: 'framerates' },
  { field: 'ageRating', header: 'Age Rating', colGroup: 'Parental Guidance' },
]
export const columnsForm = [
  { field: 'id', header: 'Neo4J UUID', hidden: true },
  { field: 'radiatorID', header: 'Radiator ID', colGroup: 'ID' },
  { field: 'nikitaVenturesID', header: 'Nikita Ventures ID', colGroup: 'SKUs' },
  { field: 'filmfriendID', header: 'Filmfriend ID' },
  { field: 'filmhubID', header: 'Filmhub ID' },
  { field: 'amazonID', header: 'Amazon ID' },
  { field: 'vimeoID', header: 'Vimeo ID' },
  { field: 'eidrID', header: 'EIDR ID' },
  { field: 'imdbID', header: 'IMDb ID' },
  { field: 'isanNr', header: 'ISAN Number' },
  { field: 'titleInternational', header: 'International title', colGroup: 'General info' },
{ field: 'titleOriginal', header: 'Original title' },
{ field: 'titleEN', header: 'English title' },
{ field: 'titleFR', header: 'French title' },
{ field: 'titleDE', header: 'German title' },
{ field: 'titleES', header: 'Spanish title' },
{ field: 'loglineEN', header: 'English logline' },
{ field: 'loglineFR', header: 'French logline' },
{ field: 'loglineDE', header: 'German logline' },
{ field: 'loglineES', header: 'Spanish logline' },
{ field: 'synopsisShortEN', header: 'English synopsis (max 300 characters)' },
{ field: 'synopsisShortFR', header: 'French synopsis (max 300 characters)' },
{ field: 'synopsisShortDE', header: 'German synopsis (max 300 characters)' },
{ field: 'synopsisShortES', header: 'Spanish synopsis (max 300 characters)' },
{ field: 'synopsisLongEN', header: 'English synopsis (max 1500 characters)' },
{ field: 'synopsisLongFR', header: 'French synopsis (max 1500 characters)' },
{ field: 'synopsisLongDE', header: 'German synopsis (max 1500 characters)' },
{ field: 'synopsisLongES', header: 'Spanish synopsis (max 1500 characters)' },
{ field: 'duration', header: 'Duration', type: FieldType.DURATION },
{ field: 'productionYear', header: 'Production year', type: FieldType.INTEGER },
{ field: 'productionMonth', header: 'Production month', type: FieldType.INTEGER },
{ field: 'worldPremiereDate', header: 'World premiere date', type: FieldType.DATE },
{ field: 'status', header: 'Status', type: FieldType.DROPDOWN, options: 'filmStatuses' },
{ field: 'framerate', header: 'Frame rate', type: FieldType.DROPDOWN, options: 'framerates' },
{ field: 'ageRating', header: 'Age rating', colGroup: 'Parental guidance' },
{ field: 'containsNudity', header: 'Contains nudity', type: FieldType.BOOLEAN },
{ field: 'containsViolence', header: 'Contains violence', type: FieldType.BOOLEAN },
{ field: 'containsDrugUse', header: 'Contains drug use', type: FieldType.BOOLEAN },
{ field: 'iMDBReviews', header: 'IMDB Reviews', type: FieldType.INTEGER, colGroup: 'Reviews' },
{ field: 'rottenTomatoesReviews', header: 'Rotten Tomatoes reviews', type: FieldType.INTEGER },
{ field: 'letterboxdReviews', header: 'Letterboxd reviews', type: FieldType.INTEGER },
{ field: 'iMDBRating', header: 'IMDB Ratings', type: FieldType.FLOAT, colGroup: 'Ratings' },
{ field: 'rottenTomatoesRating', header: 'Rotten Tomatoes rating', type: FieldType.FLOAT },
{ field: 'letterboxdRating', header: 'Letterboxd rating', type: FieldType.FLOAT },
{ field: 'filmFestivalViewers', header: 'Film festival viewers', type: FieldType.INTEGER, colGroup: 'Viewers' },
{ field: 'tvStationViewers', header: 'TV station viewers', type: FieldType.INTEGER },
{ field: 'vodViewers', header: 'VOD viewers', type: FieldType.INTEGER },
{ field: 'boxOffice', header: 'Box office', type: FieldType.INTEGER },
{ field: 'previewByFilmCriticMagazine', header: 'Magazine preview', colGroup: 'Press' },
{ field: 'previewByFilmCritic', header: 'Critic preview' },
{ field: 'reviewByFilmCriticMagazine', header: 'Magazine review' },
{ field: 'reviewByFilmCritic', header: 'Critic review' },
{ field: 'facebookFanPageURL', header: 'Facebook fanpage link', colGroup: 'Social media' },
{ field: 'instagramProfileURL', header: 'Instagram profile' },
{ field: 'twitterProfileURL', header: 'Twitter profile' },
{ field: 'websiteOfficial', header: 'Official website', colGroup: 'Links' },
{ field: 'iMDbLink', header: 'IMDB link' },
{ field: 'tMDBLink', header: 'TMDB link' },
{ field: 'letterboxdPage', header: 'Letterboxd page' },
{ field: 'justWatchPage', header: 'JustWatch page' },
{ field: 'filmfreewayPage', header: 'Filmfreeway page' },
{ field: 'audioFormat', header: 'Audio format', colGroup: 'Technical info' },
{ field: 'aspectRatio', header: 'Aspect ratio', type: FieldType.DROPDOWN, options: 'aspectRatios' },
{ field: 'masterShootingMedium', header: 'Master shooting medium', type: FieldType.DROPDOWN, options: 'shootingMediums' },
{ field: 'masterShootingFormat', header: 'Master shooting format' },
{ field: 'cameraUsed', header: 'Used camera' },
{ field: 'lensesUsed', header: 'Used lenses' },
{ field: 'editingSoftwareUsed', header: 'Editing software used' },
{ field: 'threeDSoftwareUsed', header: '3D software used' },
{ field: 'vFXSoftwareUsed', header: 'VFX software used' },
{ field: 'animationTechniqueUsed', header: 'Animation technique used' },
{ field: 'isFilmhubPosterCreated', header: 'Filmhub poster still created (2/3 - 1400x2100 - 300dpi)', type: FieldType.BOOLEAN, colGroup: 'Artwork' },
{ field: 'isFilmhubPortraitStillCreated', header: 'Filmhub portrait still created (3/4 - 1575x2100 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmhubLandscapeStillCreated', header: 'Filmhub landscape still created (2/1 - 2048x1024 - 300dpi) (', type: FieldType.BOOLEAN },
{ field: 'isFilmhubLandscapeExtra01StillCreated', header: 'FilmHub landscape still created (4/3 - 2048x1536 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmhubLandscapeExtra02StillCreated', header: 'FilmHub landscape still created (16/9 - 2048x1152 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmhubLandscapeExtra03StillCreated', header: 'FilmHub landscape still created (16/6 - 2048x768 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmhubLandscapeExtra04StillCreated', header: 'Is FilmHub Landscape Extra 04 Still Created', type: FieldType.BOOLEAN },
{ field: 'isFilmfriendPortraitCoverCreated', header: 'Filmfriend portrait cover created (1792x2560 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmfriendLandscapeCoverCreated', header: 'Filmfriend landscape cover created (2560x1440 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmfriendThumbnailCreated', header: 'Filmfriend thumbnail created (2560x1440 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmfriendSliderCreated', header: 'Filmfriend slider created (4096x1200 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmfriendBackgroundCreated', header: 'Filmfriend background created (4096x2160 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmfriendPortraitCreated', header: 'Filmfriend portrait created (1792x2560 - 300dpi)', type: FieldType.BOOLEAN },
{ field: 'isFilmfriendMaterialsOkQualityCheckPlatform', header: 'Filmfriend materials OK quality check by platform', type: FieldType.BOOLEAN },
{ field: 'filmhubLocation', header: 'Location Filmhub Artwork' },
  { field: 'filmhubMaterialsOkQualityCheckPlatform', header: 'Platform Filmhub' },
  { field: 'filmfriendLocation', header: 'Location Filmfriend Artwork' },
  { field: 'vuulrVimeoLinkFilm', header: 'Vuulr Vimeo film link', colGroup: 'Platform specific links Vimeo' },
{ field: 'vuulrVimeoLinkTrailer', header: 'Vuulr Vimeo trailer link' },
{ field: 'filmfreewayVimeoLinkFilm', header: 'Filmfreeway film link' },
{ field: 'festhomeVimeoLinkFilm', header: 'Festhome Vimeo film link' },
{ field: 'youtubeTrailerFHDRadiatorChannel', header: 'Youtube trailer FHD Radiator channel', colGroup: 'Trailer links' },
{ field: 'youtubeTrailer4KUHDRadiatorChannel', header: 'Youtube trailer 4K-UHD Radiator channel' },
{ field: 'vimeoTrailerRadiatorWebsite', header: 'Vimeo trailer Radiator website' },
{ field: 'vimeoTrailerPublic', header: 'Vimeo trailer public' },
{ field: 'vimeoScreenerProduction', header: 'Vimeo screener production', colGroup: 'Screener links' },
{ field: 'vimeoScreenerDirector', header: 'Vimeo screener director' },
{ field: 'vimeoScreenerCrew', header: 'Vimeo screener crew' },
{ field: 'vimeoScreenerDOP', header: 'Vimeo screener DOP' },
{ field: 'vimeoScreenerProgrammers', header: 'Vimeo screener programmers' },
{ field: 'vimeoScreenerBuyers', header: 'Vimeo screener buyers' },
{ field: 'vimeoScreenerPress', header: 'Vimeo screener press' },
{ field: 'vimeoOnDemandFHD', header: 'Vimeo OnDemand FHD', colGroup: 'VOD platforms links' },
{ field: 'vimeoOnDemand4KUHD', header: 'Vimeo OnDemand 4K-UHD' },
{ field: 'amazonUS', header: 'Amazon United States' },
{ field: 'amazonUK', header: 'Amazon United Kingdom' },
{ field: 'amazonDE', header: 'Amazon Germany' },
{ field: 'amazonES', header: 'Amazon Spanish' },
{ field: 'tubi', header: 'Tubi TV' },
{ field: 'dindintv', header: 'DindinTV' },
{ field: 'kisKisKeepItShortEN', header: 'Kis Kis Keep it Short channel - English subtitles burned in' },
{ field: 'kisKisKeepItShortES', header: 'Kis Kis Keep it Short channel - Spanish subtitles burned in' },
{ field: 'kisKisKeepItShortDE', header: 'Kis Kis Keep it Short channel - German subtitles burned in' },
{ field: 'kisKisKeepItShortFR', header: 'Kis Kis Keep it Short channel - French subtitles burned in' },
{ field: 'bekkesShortFilms', header: 'Bekkes Short Films channel' },
{ field: 'wocomoMovies', header: 'Wocomo Movies' },
{ field: 'wocomoHumanity', header: 'Wocomo Humanity' },
{ field: 'filmfriend', header: 'Filmfriend' },
{ field: 'amazonIMDBTV', header: 'Amazon IMDBTV' },
{ field: 'filmzie', header: 'Filmzie' },
{ field: 'fearless', header: 'Fearless' },
{ field: 'overdrive', header: 'Overdrive' },
{ field: 'kinoscope', header: 'Kinoscope' },
{ field: 'sofytv', header: 'SofyTV' },
{ field: 'daFilms', header: 'DaFilms' },
{ field: 'argo', header: 'Argo' },
{ field: 'avaLibrary', header: 'Ava Library' },
{ field: 'cinesquare', header: 'Cinesquare' },
{ field: 'cinesud', header: 'Cinesud' },
{ field: 'guideDoc', header: 'GuideDoc' },
{ field: 'soonerBelgium', header: 'Sooner Belgium' },
{ field: 'soonerGermany', header: 'Sooner Germany' },
{ field: 'criterionCollection', header: 'Criterion Collection' },
{ field: 'creedGlobalMedia', header: 'Creed Global Media' },
{ field: 'artexFilm', header: 'ArtexFilm' },
{ field: 'cineBooks', header: 'CineBooks' },
{ field: 'cinetree', header: 'Cinetree' },
{ field: 'flexNetTv', header: 'FlexNetTV' },
{ field: 'filxPremiere', header: 'FlixPremier' },
{ field: 'filmocrazy', header: 'FilmoCrazy' },
{ field: 'filmin', header: 'Filmin' },
{ field: 'gayBingeTV', header: 'GayBingeTV' },
{ field: 'movieBloc', header: 'MovieBloc' },
]
