[build]
  command = "npm i && cd api && npm i && cd ../web-react && npm i && cd .. && npm run build"
  publish = "web-react/build"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000

[template.environment]
  NEO4J_URI = "Neo4j URI (ex: bolt://localhost:7687)"
  NEO4J_USER = "Neo4j User"
  NEO4J_PASSWORD = "Neo4j Password"
  
[[redirects]]
  from = "/graphql"
  to = "https://nameless-brook-310449.eu-central-1.aws.cloud.dgraph.io/graphql"
  status = 200