import { FieldType } from '../../../common/enums'

export let emptyItem = {
  radiatorID: 'testing',
  nameInternational: '', // General info
  nameOriginal: '',
  address: '',
  about: '',
  email: '',
  telephone: '',
  dateStart: null,
  dateEnd: null,
  level: null,
  foundingYear: 2021,
  locatedInCountry: '',
  takesPlaceInCity: '',
  awards: '',
  isFIAPFAccredited: false, // Accreditations
  isAcademyAccredited: false,
  isEFAAccredited: false,
  isBaftaAccredited: false,
  isGoyaAccredited: false,
  isMeliesAccredited: false,
  isCanandianScreenGuildAccredited: false,
  isEAAAccredited: false,
  isFriends: false,
  isPartner: false,
  acceptsFilmLenghts: '', // Film Requirements
  acceptsFilmGenre01: '',
  acceptsFilmGenre02: '',
  acceptsFilmGenre03: '',
  deadlineMonth: '',
  rulesAndRegulations: '',
  premiereRequirement: '',
  filmAge: '',
  organisers: '', // Management
  directors: '',
  seniorProgrammer01: '',
  seniorProgrammer02: '',
  seniorProgrammer03: '',
  shortsProgrammer01: '',
  shortsProgrammer02: '',
  websiteMain: '', // Links
  facebookPage: '',
  instagramProfile: '',
  twitterProfile: '',
  cinandoProfile: '',
  iMDBProfile: '',
  filmfreewayLink: '',
  submissionPageOriginal: '', // Submission details
  submissionPageFilmfreeway: '',
  submissionDateEarly: null,
  submissionDateRegular: null,
  submissionDateLate: null,
  submissionFeeEarly: null,
  submissionFeeRegular: null,
  submissionFeesLate: null,
  submissionRegulations: '',
  venue01: '', // Venues
  venue02: '',
  venue03: '',
  venue04: '',
  venue05: '',
  selectionLaurel: '', // Laurels
  awardLaurel: '',
  comments: '',
}
export const columnsTable = [
  { field: 'radiatorID', header: 'Radiator ID', colGroup: 'ID' },
  { field: 'id', header: 'Neo4J UUID', hidden: true },
  { field: 'nameInternational', header: 'International Name', colGroup: 'General Info', isDefault: true },
  { field: 'address', header: 'Address' },
  { field: 'about', header: 'About' },
  { field: 'email', header: 'Email' },
  { field: 'telephone', header: 'Telephone' },
  { field: 'level', header: 'Level' },
  { field: 'foundingYear', header: 'Founding year' },
  { field: 'locatedInCountry', header: 'Country', isDefault: true },
  { field: 'takesPlaceInCity', header: 'City' },
  { field: 'acceptsFilmLenghts', header: 'Film lengths', colGroup: 'Film Requirements' },
  { field: 'acceptsFilmGenre01', header: 'Genre 01' },
  { field: 'rulesAndRegulations', header: 'Rules and regulations' },
  { field: 'premiereRequirement', header: 'Premiere requirement', isDefault: true },
  { field: 'filmAge', header: 'Film Age' },
]

export const columnsForm = [
  { field: 'id', header: 'Neo4J UUID', hidden: true },
{ field: 'radiatorID', header: 'Radiator ID', colGroup: 'ID' },
{ field: 'nameInternational', header: 'International name', colGroup: 'General info' },
{ field: 'nameOriginal', header: 'Original name' },
{ field: 'address', header: 'Address' },
{ field: 'about', header: 'About', type: FieldType.TEXTAREA },
{ field: 'email', header: 'Email', type: FieldType.EMAIL },
{ field: 'telephone', header: 'Telephone' },
{ field: 'dateStart', header: 'Start date', type: FieldType.DATE },
{ field: 'dateEnd', header: 'End date', type: FieldType.DATE },
{ field: 'level', header: 'Level' },
{ field: 'foundingYear', header: 'Founding year', type: FieldType.INTEGER },
{ field: 'locatedInCountry', header: 'Country', type: FieldType.DROPDOWN, options: 'countries' },
{ field: 'takesPlaceInCity', header: 'City' },
{ field: 'awards', header: 'Awards' },
{ field: 'isFIAPFAccredited', header: 'FIAPF', colGroup: 'Accreditations', type: FieldType.BOOLEAN },
{ field: 'isAcademyAccredited', header: 'Academy', type: FieldType.BOOLEAN },
{ field: 'isEFAAccredited', header: 'EFA', type: FieldType.BOOLEAN },
{ field: 'isBaftaAccredited', header: 'Bafta', type: FieldType.BOOLEAN },
{ field: 'isMeliesAccredited', header: 'Méliès', type: FieldType.BOOLEAN },
{ field: 'isCanandianScreenGuildAccredited', header: 'Canandian Screen Guild', type: FieldType.BOOLEAN },
{ field: 'isEAAAccredited', header: 'EAA', type: FieldType.BOOLEAN },
{ field: 'isFriends', header: 'Friends', type: FieldType.BOOLEAN },
{ field: 'isPartner', header: 'Partner', type: FieldType.BOOLEAN },
{ field: 'acceptsFilmLenghts', header: 'Film lengths', colGroup: 'Film Requirements', type: FieldType.DROPDOWN, options: 'filmLengths' },
{ field: 'acceptsFilmGenre01', header: 'Genre 01', type: FieldType.DROPDOWN, options: 'filmGenres' },
{ field: 'acceptsFilmGenre02', header: 'Genre 02', type: FieldType.DROPDOWN, options: 'filmGenres' },
{ field: 'acceptsFilmGenre03', header: 'Genre 03', type: FieldType.DROPDOWN, options: 'filmGenres' },
{ field: 'deadlineMonth', header: 'Deadline month' },
{ field: 'rulesAndRegulations', header: 'Rules and regulations', type: FieldType.TEXTAREA },
{ field: 'premiereRequirement', header: 'Premiere requirement', type: FieldType.DROPDOWN, options: 'premierRequirements' },
{ field: 'filmAge', header: 'Film Age', type: FieldType.DROPDOWN, options: 'filmAges' },
{ field: 'organisers', header: 'Organizers', colGroup: 'Management' },
{ field: 'artisticDirector', header: 'Artistic director' },
{ field: 'president', header: 'President' },
{ field: 'founder', header: 'Founder' },
{ field: 'programManager', header: 'Program manager' },
{ field: 'seniorProgrammer01', header: 'Senior programmer 01' },
{ field: 'seniorProgrammer02', header: 'Senior programmer 02' },
{ field: 'seniorProgrammer03', header: 'Senior programmer 03' },
{ field: 'shortsProgrammer01', header: 'Shorts programmer 01' },
{ field: 'shortsProgrammer02', header: 'Shorts programmer 02' },
{ field: 'websiteMain', header: 'Main website', colGroup: 'Links' },
{ field: 'facebookPage', header: 'Facebook page' },
{ field: 'instagramProfile', header: 'Instagram profile' },
{ field: 'twitterProfile', header: 'Twitter profile' },
{ field: 'cinandoProfile', header: 'Cinando page' },
{ field: 'iMDBProfile', header: 'IMDB page' },
{ field: 'filmfreewayLink', header: 'Filmfreeway page' },
{ field: 'submissionPageOriginal', header: 'Submission link original', colGroup: 'Submission details' },
{ field: 'submissionPageFilmfreeway', header: 'Submission link Filmfreeway' },
{ field: 'submissionDateEarly', header: 'Submission date early', type: FieldType.DATE },
{ field: 'submissionDateRegular', header: 'Submission date regular', type: FieldType.DATE },
{ field: 'submissionDateLate', header: 'Submission date date', type: FieldType.DATE },
{ field: 'submissionFeeCurrency', header: 'Submission Fee Currency'},
  { field: 'submissionFeeEarly', header: 'Submission Fee Early ($)', type: FieldType.CURRENCY },
  { field: 'submissionFeeRegular', header: 'Submission fee regular ($)', type: FieldType.CURRENCY },
  { field: 'submissionFeesLate', header: 'Submission fee late ($)', type: FieldType.CURRENCY },
  { field: 'submissionRegulations', header: 'Submission regulations', type: FieldType.TEXTAREA },
  { field: 'venue01', header: 'Venue 01', colGroup: 'Venues' },
  { field: 'venue02', header: 'Venue 02' },
  { field: 'venue03', header: 'Venue 03' },
  { field: 'venue04', header: 'Venue 04' },
  { field: 'venue05', header: 'Venue 05' },
  { field: 'selectionLaurel', header: 'Selection laurel', colGroup: 'Laurels' },
  { field: 'awardLaurel', header: 'Award laurel' },
  { field: 'comments', header: 'Comments', colGroup: 'Comments', type: FieldType.TEXTAREA },
]
