import { FieldType } from '../../../../common/enums'
import * as ModelsProfession from './personProfessionRelationship'
import * as QueriesProfession from '../queries/personProfessionRelationship'

export let emptyItem = {
  radiatorID: 'Testing',
}

export const columnsTable = [
  { field: 'radiatorID', header: 'Radiator ID', colGroup: 'ID' },
  { field: 'id', header: 'Neo4J UUID', hidden: true },
  { field: 'displayName', header: 'Display Name', colGroup: 'Contact Info', isDefault: true },
  { field: 'emailMain', header: 'Email Main', isDefault: true },
  { field: 'addressHomeCountryIso', header: 'Address Home Country ISO', isDefault: true },
  { field: 'phoneFix', header: 'Phone Fix' },
  { field: 'preferredLanguage', header: 'Preferred Language' },
]
export const columnsForm = [
  { field: 'id', header: 'Neo4J UUID', hidden: true },
  { field: 'radiatorID', header: 'Radiator ID', colGroup: 'ID' },
  { field: 'displayName', header: 'Display Name', colGroup: 'Contact Info' },
  { field: 'emailMain', header: 'Email Main' },
  { field: 'prefixEmail', header: 'Prefix Email' },
  { field: 'emailPreferred', header: 'Email Preferred' },
  { field: 'emailHyperlink', header: 'Email Hyperlink' },
  { field: 'nameFirstName', header: 'First Name' },
  { field: 'nameLastName', header: 'Last Name' },
  { field: 'nameFullName', header: 'Full Name' },
  { field: 'nameNickname', header: 'Nick Name' },
  { field: 'biographyEN', header: 'Biography EN' },
  { field: 'biographyFR', header: 'Biography FR' },
  { field: 'phoneFix', header: 'Phone Fix' },
  { field: 'peplePhoneMobile', header: 'Mobile Phone' },
  { field: 'preferredLanguage', header: 'Preferred Language' },
  { field: 'profession', header: 'Profession', colGroup: 'Other Info' },
  { field: 'profession01', header: 'Profession 01' },
  { field: 'profession02', header: 'Profession 02' },
  { field: 'languagesSpoken', header: 'Languages Spoken' },
  { field: 'addressHomeCity', header: 'Address Home City', colGroup: 'Address Info' },
  { field: 'addressHomeCountryEN', header: 'Address Home Country EN' },
  { field: 'addressHomeCountryIso', header: 'Address Home Country ISO' },
  { field: 'addressHomeStreet01', header: 'Address Home Street 01' },
  { field: 'addressHomeStreet02', header: 'Address Home Street 02' },
  { field: 'addressHomeZip', header: 'Address Home Zip' },
  { field: 'nameOrganisation01', header: 'Name Organisation 01' },
  { field: 'nameOrganisation02', header: 'Name Organisation 02' },
  { field: 'websiteMain', header: 'Website Main', colGroup: 'Social Media' },
  { field: 'imdbProfile', header: 'Imdb Profile' },
  { field: 'linkedinProfile', header: 'Linkedin Profile' },
  { field: 'vimeoProfile', header: 'Vimeo Profile' },
  { field: 'instagramProfile', header: 'Instagram Profile' },
  { field: 'twitterProfile', header: 'Twitter Profile' },
  { field: 'facebookProfile', header: 'Facebook Profile' },
  { field: 'socialMediaOther', header: 'Social Media Other' },
  { field: 'bank01Name', header: 'Bank Name', colGroup: 'Bank Information' },
  { field: 'bank01Code', header: 'Bank Code' },
  { field: 'bank01BicCode', header: 'Bank Bic Code' },
  { field: 'bank01HolderName', header: 'Bank Holder Name' },
  { field: 'bank01IbanNr', header: 'Bank Iban Number' },
  { field: 'bank01IbanCountryCode', header: 'Bank Iban Country Code' },
  { field: 'bank01AccountCountry', header: 'Bank Account Country' },
  { field: 'bank01AccountAddress', header: 'Bank Account Address' },
  { field: 'payPalAccount', header: 'Paypal Account' },
  { field: 'hasProfessions', header: 'Professions', colGroup: 'Professions', type: FieldType.DROPDOWN, options: 'personProfessions', isRelationship: true, models: ModelsProfession, queries: QueriesProfession },
]
