import { FieldType } from '../../../common/enums'

export let emptyItem = {
  radiatorID: 'Testing',
  titleInternational: '',
  titleOriginal: '',
  titleEN: '',
  titleFR: '',
  titleDE: '',
  titleES: '',
  loglineEN: '',
  loglineFR: '',
  loglineDE: '',
  loglineES: '',
  synopsisShortEN: '',
  synopsisShortFR: '',
  synopsisShortDE: '',
  synopsisShortES: '',
  synopsisLongEN: '',
  synopsisLongFR: '',
  synopsisLongDE: '',
  synopsisLongES: '',
  duration: 0,
  productionYear: 0,
  productionMonth: 0,
  worldPremiereDate: null,
  status: null,
  framerate: null,
  ageRating: '',
  containsNudity: null,
  containsViolence: null,
  containsDrugUse: null,
  iMDBReviews: null,
  rottenTomatoesReviews: null,
  letterboxdReviews: null,
  iMDBRating: null,
  rottenTomatoesRating: null,
  letterboxdRating: null,
  filmFestivalViewers: null,
  tvStationViewers: null,
  vodViewers: null,
  boxOffice: null,
  previewByFilmCriticMagazine: '',
  previewByFilmCritic: '',
  reviewByFilmCriticMagazine: '',
  reviewByFilmCritic: '',
  facebookFanPageURL: '',
  instagramProfileURL: '',
  twitterProfileURL: '',
  websiteOfficial: '',
  iMDbLink: '',
  tMDBLink: '',
  letterboxdPage: '',
  justWatchPage: '',
  filmfreewayPage: '',
  audioFormat: '',
  aspectRatio: null,
  masterShootingMedium: null,
  masterShootingFormat: '',
  cameraUsed: '',
  lensesUsed: '',
  editingSoftwareUsed: '',
  threeDSoftwareUsed: '',
  vFXSoftwareUsed: '',
  animationTechniqueUsed: '',
  isFilmhubPosterCreated: null,
  isFilmhubPortraitStillCreated: null,
  isFilmhubLandscapeStillCreated: null,
  isFilmhubLandscapeExtra01StillCreated: null,
  isFilmhubLandscapeExtra02StillCreated: null,
  isFilmhubLandscapeExtra03StillCreated: null,
  isFilmhubLandscapeExtra04StillCreated: null,
  isFilmfriendPortraitCoverCreated: null,
  isFilmfriendLandscapeCoverCreated: null,
  isFilmfriendThumbnailCreated: null,
  isFilmfriendSliderCreated: null,
  isFilmfriendBackgroundCreated: null,
  isFilmfriendMaterialsOkQualityCheckPlatform: null,
  filmhubPosterLocation: '',
  filmhubPortraitStillLocation: '',
  filmhubLandscapeStillLocation: '',
  filmhubLandscapeExtra01StillLocation: '',
  filmhubLandscapeExtra02StillLocation: '',
  filmhubLandscapeExtra03StillLocation: '',
  filmhubLandscapeExtra04StillLocation: '',
  filmhubMaterialsOkQualityCheckPlatform: '',
  filmfriendPortraitCoverLocation: '',
  filmfriendLandscapeCoverLocation: '',
  filmfriendThumbnailLocation: '',
  filmfriendSliderLocation: '',
  filmfriendBackgroundLocation: '',
  vuulrVimeoLinkFilm: '',
  vuulrVimeoLinkTrailer: '',
  filmfreewayVimeoLinkFilm: '',
  festhomeVimeoLinkFilm: '',
  youtubeTrailerFHDRadiatorChannel: '',
  youtubeTrailer4KUHDRadiatorChannel: '',
  vimeoTrailerRadiatorWebsite: '',
  vimeoTrailerPublic: '',
  vimeoScreenerProduction: '',
  vimeoScreenerDirector: '',
  vimeoScreenerCrew: '',
  vimeoScreenerDOP: '',
  vimeoScreenerProgrammers: '',
  vimeoScreenerBuyers: '',
  vimeoScreenerPress: '',
  vimeoOnDemandFHD: '',
  vimeoOnDemand4KUHD: '',
  amazonUS: '',
  amazonUK: '',
  amazonDE: '',
  amazonES: '',
  tubi: '',
  dindintv: '',
  kisKisKeepItShortEN: '',
  kisKisKeepItShortES: '',
  kisKisKeepItShortDE: '',
  kisKisKeepItShortFR: '',
  bekkesShortFilms: '',
  wocomoMovies: '',
  wocomoHumanity: '',
  filmfriend: '',
  amazonIMDBTV: '',
  filmzie: '',
  fearless: '',
  overdrive: '',
  kinoscope: '',
  sofytv: '',
  daFilms: '',
  argo: '',
  avaLibrary: '',
  cinesquare: '',
  cinesud: '',
  guideDoc: '',
  soonerBelgium: '',
  soonerGermany: '',
  criterionCollection: '',
  creedGlobalMedia: '',
  artexFilm: '',
  cineBooks: '',
  cinetree: '',
  flexNetTv: '',
  filxPremiere: '',
  filmocrazy: '',
  filmin: '',
  gayBingeTV: '',
  movieBloc: '',

}

export const columns = [
  { field: 'radiatorID', header: 'Radiator ID', colGroup: 'ID' },
  { field: 'id', header: 'Neo4J UUID', hidden: true },
  { field: 'titleInternational', header: 'International Title', colGroup: 'General Info' , isDefault:true },
  { field: 'countSubmittedToFilmFestivals', header: 'Festival Submissions'  , isDefault:true },
  { field: 'countSelectedAtFilmFestivals', header: 'Festival Selections'  , isDefault:true },
  { field: 'countShortlistedAtFilmFestivals', header: 'Festival Shortlist'  , isDefault:true },
  { field: 'countToSubmitToFilmFestivals', header: 'Festivals To Submit'  , isDefault:true },
  { field: 'countNotSelectedAtFilmFestivals', header: 'Festivals Not Selected'  , isDefault:true },
  { field: 'countFestivalApplications', header: 'Total Number of Applications'  , isDefault:true },
]
export const columnsAll = [
  { field: 'id', header: 'Neo4J UUID', hidden: true  },
  { field: 'radiatorID', header: 'Film Radiator ID', colGroup: 'ID' },
  { field: 'applicationDate', header: 'Application Date', type: FieldType.DATE, colGroup: 'General Info' },
  { field: 'feeUSD', header: 'Fee USD', type: FieldType.FLOAT },
  { field: 'feeEUR', header: 'Fee EUR', type: FieldType.FLOAT },
  { field: 'waivedAmountUSD', header: 'Waived Amount USD', type: FieldType.FLOAT },
  { field: 'waivedAmountEUR', header: 'Waived Amount EUR', type: FieldType.FLOAT },
]
